[package]
name = "sieve-of-eratosthenes"
version = "0.1.1"
edition = "2024"
description = "A standard implementation of the Sieve of Eratosthenes"
license = "Unlicense"
repository = "https://github.com/michaeltinsley/rust-fundamentals"

[dependencies]

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "sieve-of-eratosthenes-benchmark"
harness = false
